ARG MINIO_CLIENT_IMAGE=minio/mc:latest
FROM ${MINIO_CLIENT_IMAGE}

LABEL org.opencontainers.image.title="NextStorage Client"
LABEL org.opencontainers.image.description="NextLife MinIO client image for bucket initialization and storage administration"
LABEL org.opencontainers.image.source="https://github.com/muratdelen/NextStorage-Core"
LABEL org.opencontainers.image.vendor="NextLife"
